---
# syslog-summary package has been removed after Debian10/Ubuntu20.04
# and no direct replacement => basic one
# https://tracker.debian.org/pkg/syslog-summary
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=198762

- name: Logcheck additional configuration - ntpd ignore
  ansible.builtin.copy:
    src: ntpd
    dest: /etc/logcheck/ignore.d.server/ntpd
    mode: '0644'

- name: Logcheck additional configuration - ignore rules
  ansible.builtin.copy:
    src: logcheck-local-ignores
    dest: /etc/logcheck/ignore.d.server/local-rules
    mode: '0644'

- name: Debian-docker | check if /var/log/syslog exists
  ansible.builtin.stat:
    path: /var/log/syslog
  register: syslogfile
- name: Debian-docker | ensure /var/log/syslog file exists for following validate
  ansible.builtin.file:
    dest: /var/log/syslog
    mode: '0644'
    state: touch
  when: >
    (ansible_facts['virtualization_type'] is defined and ansible_facts['virtualization_type'] == "docker") and
    ((ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version']|int >= 9) or
      (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version']|int >= 18)
    ) and not syslogfile.stat.exists

- name: Logcheck replace rules
  ansible.builtin.template:
    src: logcheck.replace.j2
    dest: /etc/logcheck/logcheck.replace
    mode: '0644'
    # FIXME! seems to create random errors
    # validate: 'sed -f %s /var/log/syslog > /dev/null'
    #
- name: Validate Logcheck replace rules
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      tail -n10 /var/log/syslog | sed -f /etc/logcheck/logcheck.replace > /dev/null
    executable: /bin/bash
  changed_when: false

- name: Review Logcheck configuration
  ansible.builtin.replace:
    dest: '/etc/logcheck/logcheck.conf'
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    mode: '0644'
    ## Error: Config file /tmp/tmp32Yy_d unreadable or does not exists
    # validate: 'sudo -u logcheck logcheck -t -d -o -c %s'
  with_items:
    - { regexp: '^#SORTUNIQ=0', replace: 'SORTUNIQ=1' }
    - { regexp: '^#SYSLOGSUMMARY=0', replace: 'SYSLOGSUMMARY=1' }
    - { regexp: '^(#?)TMP=".*"', replace: 'TMP=/tmp/logcheck-temp-files' }

- name: Ensure TMP dir exists now
  ansible.builtin.file:
    path: /tmp/logcheck-temp-files
    owner: logcheck
    mode: '0700'
    state: directory

- name: Ensure TMP dir exists at reboot
  ansible.builtin.lineinfile:
    dest: /etc/cron.d/logcheck
    line: '@reboot         logcheck    [ ! -d /tmp/logcheck-temp-files ] && install -d -o logcheck -m 700 /tmp/logcheck-temp-files'
    insertafter: '^@reboot         logcheck    if [ -x /usr/sbin/logcheck ]; then nice -n10 /usr/sbin/logcheck -R; fi'
    mode: '0644'

- name: Add log files for logcheck to check
  ansible.builtin.lineinfile:
    dest: /etc/logcheck/logcheck.logfiles
    line: "{{ item }}"
    mode: '0644'
    backup: "{{ harden_backup | default(false) }}"
  with_items: "{{ harden_logcheck_extra_logfiles }}"

- name: Check if logcheck patched
  ansible.builtin.stat:
    path: /usr/sbin/.logcheck-ansible-harden-patch
  register: lpatch
- name: Logcheck patching
  when: not lpatch.stat.exists
  block:
    - name: Patch logcheck to do replacement
      ansible.posix.patch:
        src: "{{ harden_logcheck_patch }}"
        dest: /usr/sbin/logcheck
        remote_src: no
        backup: "{{ harden_backup | default(false) }}"
      failed_when: false
    - name: Check logcheck patched
      ansible.builtin.command:
        cmd: grep logcheck.replace /usr/sbin/logcheck
      changed_when: false
    - name: Backup patched logcheck
      ansible.builtin.copy:
        src: /usr/sbin/logcheck
        dest: /usr/sbin/logcheck.patched
        mode: '0700'
        remote_src: true
    - name: Add patch marker
      ansible.builtin.file:
        dest: /usr/sbin/.logcheck-ansible-harden-patch
        mode: '0644'
        state: touch

# FIXME!
# - name: Add support for fail2ban date format to syslog-summary
#   ansible.builtin.lineinfile:
#     dest: /usr/bin/syslog-summary
#     line: '\tre.compile(r"^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] [0-9][0-9]:[0-9][0-9]:[0-9][0-9],[0-9]+ "),'
#     insertbefore: '^\]$'
#     backup: yes

- name: Review logcheck frequency
  ansible.builtin.replace:
    dest: /etc/cron.d/logcheck
    regexp: '^2 \* \* \* \*       logcheck'
    replace: '2 {{ harden_logcheck_hours }} * * *       logcheck'
    mode: '0644'
  when: harden_logcheck_hours is defined and harden_logcheck_hours != '*'
## http://wiki.bluelightav.org/display/BLUE/Logcheck+administration
- name: Review Logcheck cron on reboot
  ansible.builtin.replace:
    dest: /etc/cron.d/logcheck
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
    mode: '0644'
  with_items:
    - { regexp: '^@reboot         logcheck    if [ -x /usr/sbin/logcheck ]; then nice -n10 /usr/sbin/logcheck -R; fi',
        replace: '@reboot         logcheck    if [ -x /usr/sbin/logcheck ]; then sleep 10; nice -n10 /usr/sbin/logcheck -R; fi'
    }

- name: Ensure pid directory for logcheck user at reboot (systemd-tmpfiles)
  ansible.builtin.lineinfile:
    dest: /etc/tmpfiles.d/logcheck.conf
    line: '    d    /run/logcheck   0755 logcheck logcheck - -'
    mode: '0644'
    create: yes
  when: ansible_facts['service_mgr'] == 'systemd'

- name: Alternate syslog-summary
  when: >
    (ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version']|int > 10) or
    (ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_major_version']|int > 20)
  block:
    - name: Add basic replacement for syslog-summary if no package
      ansible.builtin.template:
        src: syslog-summary.j2
        dest: /usr/bin/syslog-summary
        mode: '0755'
    - name: Redirect stderr to tmp file
      ansible.builtin.replace:
        path: /usr/sbin/logcheck
        regexp: '\$SYSLOG_SUMMARY "\$TMPDIR\/checked" \| \\'
        replace: '$SYSLOG_SUMMARY "$TMPDIR/checked" 2>/tmp/syslog-summary.err | \\'
        backup: true
        # backup: "{{ harden_backup | default(false) }}"
        mode: '0755'
