---

- name: Check if grub is present
  ansible.builtin.stat:
    path: /etc/default/grub
  register: hasgrub

## linux.yml: disable usb storage drivers - grub

## Enable IOMMU, requires VT-d - DMA attack coverage. partial? perf impact?
## ANSSI R11
## https://www.sstic.org/2010/presentation/Analyse_de_l_efficacite_du_service_fourni_par_une_IOMMU/
## https://www.cs.tau.ac.il/~mad/publications/asplos2016-iommu.pdf
## http://www.stewin.org/papers/dimvap15-stewin.pdf
- name: Update grub settings
  when: >
    not (ansible_facts['virtualization_type'] is defined and
          (ansible_facts['virtualization_type'] == "lxc" or ansible_facts['virtualization_type'] == "docker")
        ) and hasgrub.stat.exists
  block:
    - name: Enable IOMMU in grub
      ansible.builtin.replace:
        dest: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX="(.*)"'
        replace: 'GRUB_CMDLINE_LINUX="\1 iommu=force"'
        mode: '0644'
        backup: "{{ harden_backup | default(false) }}"
      notify:
        - Refresh grub config
      when: harden_enable_iommu_force
    - name: Enable bpf in grub
      ansible.builtin.replace:
        dest: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX="(.*)"'
        replace: 'GRUB_CMDLINE_LINUX="\1 lsm=bpf"'
        mode: '0644'
        backup: "{{ harden_backup | default(false) }}"
      notify:
        - Refresh grub config
      when: harden_enable_grub_bpf
    - name: Enable grub password
      ansible.builtin.lineinfile:
        dest: /etc/grub.d/45_password
        regexp: '^password --md5 .*'
        line: "password --md5 {{ harden_grub_md5password }}"
        mode: '0644'
        create: yes
      notify:
        - Refresh grub config
      when: ansible_facts['os_family'] == 'Debian' and harden_grub_md5password is defined and harden_grub_md5password | string
    - name: Enable grub password
      ansible.builtin.lineinfile:
        dest: /boot/grub/grub.cfg
        regexp: '^password --md5 .*'
        line: "password --md5 {{ harden_grub_md5password }}"
        mode: '0644'
        create: yes
      when: ansible_facts['os_family'] == "RedHat" and harden_grub_md5password is defined and harden_grub_md5password | string
