---
name: Galaxy-NG Roles Import

on:
  release:
    types: [created, edited, published, released]
  push:
    tags:
      - '*'

permissions: {}

jobs:
  build:
    name: Galaxy Role Importer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # tag=v5.0.0
        with:
          submodules: true
          fetch-depth: 0

      - name: 'Release on galaxy'
        uses: ansible-actions/ansible-galaxy-action@6583ad2de12dd12433683826fe7ba26a28d3382f
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
          galaxy_version: 'main'
